config/routes.rb
Regiauto::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'auth', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }  

  resources :process_registers do
    get 'delivery_status', :on => :member 
  end
   
  resources :vehicles, :hypothecs, :proprietary_registers, :sale_registers, :books, :main_registers, :proprietaries
  resources :home, :only => :index 
  

  root :to => "home#index"

end

app/models/process_register.rb
class ProcessRegister < ActiveRecord::Base
  
  after_update :book_register
  
  has_one :main_register
  has_one :sale_register
  has_one :hypothec
  has_one :proprietary_register
  
  belongs_to :proprietary
  belongs_to :vehicle
  
  validates_presence_of :register_type, :process_status, :proprietary_id, :vehicle_id
  
  accepts_nested_attributes_for :main_register, :allow_destroy => true
  accepts_nested_attributes_for :sale_register, :allow_destroy => true
  accepts_nested_attributes_for :hypothec, :allow_destroy => true
  accepts_nested_attributes_for :proprietary_register, :allow_destroy => true    
  
  REGISTERTYPE = %w( compra_venda registo_inicial hipoteca registo_propriedade)

  scope :correct, :conditions => {:process_status => "Conforme"}
  scope :incorrect_closed, where(:process_status => ["Inconforme", "Fechado"], :delivery_status => false)
  scope :opened, :conditions => {:process_status => "Aberto"}
  scope :aproved, :conditions => {:process_status => "Aprovado"}
  scope :opened_aproved_reproved, :conditions =>{:process_status => ["Aberto", "Aprovado","Reprovado"]} 
  
  private
  def book_register
    if self.process_status == "Aprovado"
      book = Book.where("vehicle_id = ?", "#{self.vehicle_id}")
      if book.nil?
        Book.create(:proprietary_id => self.proprietary_id, :vehicle_id => self.vehicle_id, :process_register_id => self.id)
      else
        book.update_all(:proprietary_id => self.proprietary_id, :process_register_id => self.id)
      end
    end
  end
  
  def self.search(search)
    if search.nil?
      scoped
    elsif search.empty?
      scoped
    else
      where('id = ?', "#{search}")
    end
  end

  def self.status(profile)
    if profile == "Atendedor"
      %w(Aberto)
    elsif profile == "Analista"
       %w(Conforme Inconforme Fechado)
    else
      %w(Aprovado Reprovado)
    end
  end
  
end

app/controllers/process_registers_controller.rb
class ProcessRegistersController < ApplicationController  
  before_filter :authenticate_user!
  #load_and_authorize_resource
  
  # GET /process_registers
  # GET /process_registers.xml
  def index
    if current_user.profile == "Atendedor"
      @process_registers = ProcessRegister.search(params[:search]).incorrect_closed.paginate(:page => params[:page], :per_page => 10, :order => :id, :include =>[:proprietary, :vehicle])
    elsif current_user.profile == "Analista"
      @process_registers = ProcessRegister.search(params[:search]).opened_aproved_reproved.paginate(:page => params[:page], :per_page => 10, :order => :id, :include =>[:proprietary, :vehicle])
    elsif current_user.profile == "Conservador"
      @process_registers = ProcessRegister.search(params[:search]).correct.paginate(:page => params[:page], :per_page => 10, :order => :id, :include =>[:proprietary, :vehicle])
    else
      @process_registers = ProcessRegister.search(params[:search]).paginate(:page => params[:page], :per_page => 10, :order => :id, :include =>[:proprietary, :vehicle])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @process_registers }
      format.js
    end
  end

  # GET /process_registers/1
  # GET /process_registers/1.xml
  def show
    @process_register = ProcessRegister.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @process_register }
      format.pdf
    end
  end

  # GET /process_registers/new
  # GET /process_registers/new.xml
  def new
    @process_register = ProcessRegister.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @process_register }
    end
  end

  # GET /process_registers/1/edit
  def edit
    @process_register = ProcessRegister.find(params[:id])
  end

  # POST /process_registers
  # POST /process_registers.xml
  def create
    @process_register = ProcessRegister.new(params[:process_register])

    respond_to do |format|
      if @process_register.save
        format.html { redirect_to(@process_register, :notice => 'Process register was successfully created.') }
        format.xml  { render :xml => @process_register, :status => :created, :location => @process_register }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @process_register.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /process_registers/1
  # PUT /process_registers/1.xml
  
  def update
    @process_register = ProcessRegister.find(params[:id])

    respond_to do |format|
      if @process_register.update_attributes(params[:process_register])
        format.html { redirect_to(@process_register, :notice => 'Process register was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @process_register.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /process_registers/1
  # DELETE /process_registers/1.xml
  def destroy
    @process_register = ProcessRegister.find(params[:id])
    @process_register.destroy

    respond_to do |format|
      format.html { redirect_to(process_registers_url) }
      format.xml  { head :ok }
    end
  end
  
  # Actualizar o campo devivery_status
  def delivery_status
    @process_register = ProcessRegister.find(params[:id])
    if @process_register.update_attributes(:delivery_status =>true)
        redirect_to(@process_register, :notice => 'Processo de Entrega Executado com Sucesso')
    end  
  end
  
end

app/helpers/process_registers_helper.rb
module ProcessRegistersHelper
end

app/views/process_registers/_form.html.erb
<%= simple_form_for(@process_register) do |f| %>
	<% if @process_register.errors.any? %>
	  <div id="error_explanation">
	    <h2>Não foi possivel gravar o processo <%= pluralize(@process_register.errors.count, "erro") %> :</h2>
	    <ul>
	      <% @process_register.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	    </ul>
	  </div>
	<% end %>

	<%= f.hidden_field :delivery_status, :value => false %>

	<div class="field_proprietary">
		<%= f.label :proprietary_id, :required => false %>
		<%= f.text_field :proprietary_id, "data-pre" => Array(@process_register.proprietary).map(&:attributes).to_json %>
		<span class="lnk"><%= link_to "+", new_proprietary_path, :class => "btn" %></span>
	</div>
	<div class="field_vehicle">
		<%= f.label :vehicle_id, :required => false %>
		<%= f.text_field :vehicle_id, "data-pre" => Array(@process_register.vehicle).map(&:attributes).to_json %>
		<div class="lnk"><%= link_to "+", new_vehicle_path, :class => "btn" %></div>
	</div>
	<div class="field">
		<%= f.input :register_type, :collection => ProcessRegister::REGISTERTYPE, :prompt => "Seleccione", :required => false, :input_html => { :style => "width: 218px;"} %>
	</div>
	<div class="field">
		<%= f.input :process_status, :collection => ProcessRegister::status(current_user.profile), :prompt => "Seleccione", :required => false, :input_html => { :style => "width: 218px;"} %>
	</div>
	<div class="field">
		<%= f.input :notes, :as => :text %>
	</div>
	<div class="field">
		<%= f.input :documents %>
	</div>
  
  <div class="process_menu">                                                             
	<ul>
		<li class="main_register"><%= link_to_add_fields t(:add_main_register, :scope => "process_registers.new"), f, :main_register %></li>
  		<li class="sale_register"><%= link_to_add_fields t(:add_sale_register, :scope => "process_registers.new"), f, :sale_register %></li>
  		<li class="hypothec"><%= link_to_add_fields t(:add_hypothec_register, :scope => "process_registers.new"), f, :hypothec %></li>
  		<li class="proprietary_register"><%= link_to_add_fields t(:add_proprietary_register, :scope => "process_registers.new"), f, :proprietary_register %></li>
	</ul>
  </div>
  <div class="field">
	<%= f.simple_fields_for :main_register do |mr| %>
		<%= render 'main_register_fields', :f => mr %>
	<% end %>
  </div>
 
  <div class="field">
	<%= f.simple_fields_for :sale_register do |sr| %>
		<%= render 'sale_register_fields', :f => sr %>
	<% end %>
  </div>

  <div class="field">
	<%= f.simple_fields_for :hypothec do |h| %>
		<%= render 'hypothec_fields', :f => h %>
	<% end %>
  </div>

  <div class="field">
	<%= f.simple_fields_for :proprietary_register do |h| %>
		<%= render 'proprietary_register_fields', :f => h %>
	<% end %>
  </div>
  
  <hr/>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/process_registers/_hypothec_fields.html.erb
<div class="field">
  <div class='hypothec'>
	  <%= f.input :applicant %>
	  <%= f.input :contract_document %>
	  <%= f.input :value, :input_html =>{:style => "width: 100px"} %>
	  <%= f.input :outstanding, :input_html =>{:style => "width: 100px"} %>
	  <%= f.input :dept_origin %>
	  <%= f.input :interest_rate, :input_html =>{:style => "width: 100px"} %>
  </div>
  <div class='nav'><%= link_to_remove_fields t(:remove), f %></div>
</div>

app/views/process_registers/_main_register_fields.html.erb
<div class="field">
 <div class="main_register">	
  <%= f.input :vehicle_provenience, :collection => MainRegister::PROVENIENCE, :prompt => "Seleccione"  %>
  <div class='nav'><%= link_to_remove_fields t(:remove), f %></div>
 </div>
</div>

app/views/process_registers/_process_registers.html.erb
<table>
  <tr>
    <th><%= t(:process_id, :scope => "process_registers")%></th>
    <th><%= t(:nuit, :scope => "process_registers.index")%></th>
    <th><%= t(:vehicle, :scope => "process_registers.index")%></th>
    <th><%= t(:register_type, :scope => "process_registers.index")%></th>
    <th><%= t(:process_status, :scope => "process_registers.index")%></th>
    <th><%= t(:created_at, :scope => "process_registers")%></th>
  </tr>

<% @process_registers.each do |process_register| %>
 <tr>
    <td onclick="location.href='<%= process_register_path(process_register)%>'"><%= process_register.id %></td>
    <td><%= process_register.proprietary.nuit %></td>
    <td><%= process_register.vehicle.name %></td>
    <td><%= process_register.register_type %></td>
    <td><%= process_register.process_status %></td>
    <td><%= process_register.created_at.to_formatted_s(:short) %></td>
	<% if can? :update, process_register  %>
	 <td class='links'><%= link_to image_tag('edit.gif', :alt=> "Edit"), edit_process_register_path(process_register) %></td>
	<% end %>
	<% if can? :destroy, process_register  %>
     <td class='links'><%= link_to image_tag('del.gif', :alt=> "Destroy"), process_register, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

app/views/process_registers/_proprietary_register_fields.html.erb
<div class="field">
	<div class='proprietary_register'>	
		<%= f.input :aquire_date, :as => :date  %>
	  	<%= f.input :register_dute %>
	  	<%= f.input :value, :input_html =>{:style => "width:100px"} %>
	</div>
  	<div class='nav'><%= link_to_remove_fields t(:remove), f %></div>
</div>

app/views/process_registers/_sale_register_fields.html.erb
<div class="field">
	<div class="sale_register">	<%= f.input :buy_date , :as => :date, :order => [:day, :month, :year] %>
	  <%= f.input :value %>
	  <%= f.association :seller, :collection => Proprietary.all.collect{|p| [p.name, p.id]}, :prompt => "Seleccione"%>
	  <div class='nav'><%= link_to_remove_fields t(:remove), f %></div>
	</div>
</div>
 

app/views/process_registers/edit.html.erb
<h1>Editing process_register</h1>

<%= render 'form' %>

<div class="edit_menu">
	<ul>
		<li><%= link_to 'Show', @process_register %></li> 
		<li><%= link_to 'Back', process_registers_path %></li>
	</ul>
</div>

app/views/process_registers/index.html.erb
<h1><%= t('process_registers.index.title') %></h1>

<div class="nav"><%= link_to t('process_registers.index.new_process'), new_process_register_path %></div>

<div class='search_field'>
  <%= form_tag process_registers_path, :method => 'get', :id => "search" do %>
	 <%= text_field_tag :search, params[:search], :placeholder => t(:search), :autocomplete => :off,  :id => "field_search"%>
	 <%= submit_tag t(:search), :search => nil %>
  <% end %>
</div>

<% unless @process_registers.empty? %>
  <div id="process"><%= render 'process_registers' %></div>
<% end %>

<div class='paginate'><%= will_paginate @process_registers %></div>

app/views/process_registers/index.js.erb
$('#process').html('<%= escape_javascript(render("process_registers"))%>');

app/views/process_registers/new.html.erb
<h1><%= t(".title")%></h1>

<p id="notice"><%= notice %></p>

<div class='process_register'><%= render 'form' %></div>

<div class="nav"><%= link_to t(:back), process_registers_path %></div>

app/views/process_registers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="process_register_layout">
	<p class='id'>
	  <b><%= t(:process_id, :scope => "process_registers") %>:</b>
	  <%= @process_register.id %>
	</p>
	<div class='details'>	
		<p>
		  <b><%= t(:nuit_and_name, :scope => "process_registers.show")%></b>
		 <label><%= @process_register.proprietary.nuit %></label> - 
		 <label><%= @process_register.proprietary.name %></label>
		</p>
		<p>
		  <b><%= t(:vehicle_number_plate, :scope => "process_registers.show")%></b>
		  <label><%= @process_register.vehicle.name %></label>
		</p>

		<p>
		  <b><%= t(:register_type, :scope => "process_registers.show")%></b>
		  <label><%= @process_register.register_type %></label>
		</p>

		<p>
		  <b><%= t(:process_status, :scope => "process_registers.show") %></b>
		  <label><%= @process_register.process_status %></label>
		</p>

		<p>
		  <b><%= t(:documents, :scope => "process_registers.show")%></b>
		  <label><%= @process_register.documents %></label>
		</p>
		
		<p>
		  <b><%= t(:created_at, :scope => "process_registers")%></b>
		  <label><%= @process_register.created_at%></label>
		</p>
		<p>
		  <b><%= t(:notes, :scope => "process_registers.show")%></b>
		  <label><%= @process_register.notes %></label>
		</p>
		
	</div>
</div>

<div class="edit_menu">
	<ul>
		<% if can? :edit, @process_register %>
		 <li><%= link_to t(:edit), edit_process_register_path(@process_register)%></li> 
		<% end %>
		<li><%= link_to t(:back), process_registers_path %></li>
		<li><%= link_to 'Título', process_register_path(@process_register, :format => "pdf")%></li>
		<% if can? :update, @process_register %>
		 <li><%= link_to "Entregar",  :controller => :process_registers, :action => :delivery_status %></li>
		<% end %>
	</ul>
</div>