config/routes.rb
Regiauto::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'auth', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }  

  resources :process_registers do
    get 'delivery_status', :on => :member 
  end
   
  resources :vehicles, :hypothecs, :proprietary_registers, :sale_registers, :books, :main_registers, :proprietaries
  resources :home, :only => :index 
  

  root :to => "home#index"

end

app/models/main_register.rb
class MainRegister < ActiveRecord::Base
  
  belongs_to :process_register
  
  STATUS =%w(Open Closed)
  PROVENIENCE =%w(Importado Construido Reconstruido)
  
end

app/controllers/main_registers_controller.rb
class MainRegistersController < ApplicationController
  # GET /main_registers
  # GET /main_registers.xml
  def index
    @main_registers = MainRegister.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @main_registers }
    end
  end

  # GET /main_registers/1
  # GET /main_registers/1.xml
  def show
    @main_register = MainRegister.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @main_register }
    end
  end

  # GET /main_registers/new
  # GET /main_registers/new.xml
  def new
    @main_register = MainRegister.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @main_register }
    end
  end

  # GET /main_registers/1/edit
  def edit
    @main_register = MainRegister.find(params[:id])
  end

  # POST /main_registers
  # POST /main_registers.xml
  def create
    @main_register = MainRegister.new(params[:main_register])

    respond_to do |format|
      if @main_register.save
        format.html { redirect_to(@main_register, :notice => 'Main register was successfully created.') }
        format.xml  { render :xml => @main_register, :status => :created, :location => @main_register }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @main_register.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /main_registers/1
  # PUT /main_registers/1.xml
  def update
    @main_register = MainRegister.find(params[:id])

    respond_to do |format|
      if @main_register.update_attributes(params[:main_register])
        format.html { redirect_to(@main_register, :notice => 'Main register was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @main_register.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /main_registers/1
  # DELETE /main_registers/1.xml
  def destroy
    @main_register = MainRegister.find(params[:id])
    @main_register.destroy

    respond_to do |format|
      format.html { redirect_to(main_registers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/main_registers_helper.rb
module MainRegistersHelper
end

app/views/main_registers/_form.html.erb
<div class="mainReg">
<%=field_set_tag do %>
<%= form_for @main_register do |f| %>
  <% if @main_register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@main_register.errors.count, "error") %> prohibited this main_register from being saved:</h2>
      <ul>
      	 <% @main_register.errors.full_messages.each do |msg| %>
	       <li><%= msg %></li>
	     <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field2">
  	<%= f.label :type %>
	<%= f.text_field :type %>
  </div>
  <hr/>
  <div class="actions">
    <%= f.submit "Main Register" %>
  </div>
<% end %>
<% end %>
</div>

app/views/main_registers/_vehicle.html.erb
<%= form_for (@vehicle) do |f|  %>
	<% if @vehicle.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

	      <ul>
	      <% @vehicle.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	<% end %>
	<div class="field">
		<%= f.label :name, "Number plate" %></br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :mark %></br>
		<%= f.text_field :mark %>
	</div>
	<div class="field">
		<%= f.label :model %></br>
		<%= f.text_field :model %>
	</div>
	<div class="field">
		<%= f.label :frame_number %></br>
		<%= f.text_field :frame_number %>
	</div>
	<div class="field">
		<%= f.label :engine_number %></br>
		<%= f.text_field :engine_number %>
	</div>
	<div class="field">
		<%= f.label :cylinders %></br>
		<%= f.text_field :cylinders %>
	</div>
	<div class="field">
		<%= f.label :cylinders_cc, 'Cylinder Size' %></br>
		<%= f.text_field :cylinders_cc %>
	</div>
	<div class="field">
		<%= f.label :petrol %></br>
		<%= f.text_field :petrol %>
	</div>
	<div class="field">
		<%= f.label :transmission %></br>
		<%= f.text_field :transmission %>
	</div>
	<div class="field">
		<%= f.label :pneumatic_measures %></br>
		<%= f.text_field :pneumatic_measures %>
	</div>
	<div class="field">
		<%= f.label :gross_weight %></br>
		<%= f.text_field :gross_weight %>
	</div>
	<div class="field">
		<%= f.label :tare %></br>
		<%= f.text_field :tare %>
	</div>
	<div class="field">
		<%= f.label :stocking %></br>
		<%= f.text_field :stocking %>
	</div>
	<div class="field">
		<%= f.label :color %></br>
		<%= f.text_field :color %>
	</div>
	<div class="field">
		<%= f.label :service %></br>
		<%= f.text_field :service %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/main_registers/edit.html.erb
<h1>Editing main_register</h1>

<%= render 'form' %>

<%= link_to 'Show', @main_register %> |
<%= link_to 'Back', main_registers_path %>

app/views/main_registers/index.html.erb
<%- title "Listing" -%>
<h1>Listing main_registers</h1>

<table>
  <tr>
	<th>Process Number</th>
	<th>Process Name</th>
    <th>Proprietary</th>
    <th>Vehicle provenience</th>
    <th>Vehicle</th>
    <th>Status</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @main_registers.each do |main_register| %>
  <tr>
	<td><%= main_register.id %></td>
	<td><%= main_register %></td>
    <td><%= main_register %></td>
    <td><%= main_register.vehicle_provenience %></td>
    <td><%= main_register %></td>
    <td><%= main_register %></td>
    <td><%= main_register %></td>
    <td><%= link_to 'Show', main_register %></td>
    <td><%= link_to 'Edit', edit_main_register_path(main_register) %></td>
    <td><%= link_to 'Destroy', main_register, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Main register', new_main_register_path %>

app/views/main_registers/new.html.erb
<div id="title"><h1>New main_register</h1></div>
<div id="init">
	<ul>
		<li><%= link_to "Register", new_main_register_path %></li>
		<li><%= link_to "Proprietary", new_proprietary_path, :remote => true %></li>
		<li><%= link_to "Vehicle details", new_vehicle_path, :remote => true %></li>
	</ul>
	
</div>

<div id="pty"><%= render 'form' %></div>

<%= link_to 'Back', main_registers_path %>

app/views/main_registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Proprietary:</b>
  <%= @main_register.proprietary.name %>
</p>

<p>
  <b>Vehicle provenience:</b>
  <%= @main_register.vehicle_provenience %>
</p>

<p>
  <b>Vehicle:</b>
  <%= @main_register.vehicle.name %>
</p>

<p>
  <b>Status:</b>
  <%= @main_register.status %>
</p>

<p>
  <b>Notes:</b>
  <%= @main_register.notes %>
</p>


<%= link_to 'Edit', edit_main_register_path(@main_register) %> |
<%= link_to 'Back', main_registers_path %>