config/routes.rb
Regiauto::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'auth', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }  

  resources :process_registers do
    get 'delivery_status', :on => :member 
  end
   
  resources :vehicles, :hypothecs, :proprietary_registers, :sale_registers, :books, :main_registers, :proprietaries
  resources :home, :only => :index 
  

  root :to => "home#index"

end

app/models/sale_register.rb
class SaleRegister < ActiveRecord::Base
  
  belongs_to :process_register
  
  belongs_to :seller, :class_name => "Proprietary", :foreign_key => "seller_id"
  
  validates_uniqueness_of :process_register_id
  
  validates_presence_of :buy_date, :value, :seller

  attr_accessor :phone
  
end

app/controllers/sale_registers_controller.rb
class SaleRegistersController < ApplicationController
  # GET /sale_registers
  # GET /sale_registers.xml
  def index
    @sale_registers = SaleRegister.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sale_registers }
    end
  end

  # GET /sale_registers/1
  # GET /sale_registers/1.xml
  def show
    @sale_register = SaleRegister.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sale_register }
    end
  end

  # GET /sale_registers/new
  # GET /sale_registers/new.xml
  def new
    @sale_register = SaleRegister.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sale_register }
    end
  end

  # GET /sale_registers/1/edit
  def edit
    @sale_register = SaleRegister.find(params[:id])
  end

  # POST /sale_registers
  # POST /sale_registers.xml
  def create
    @sale_register = SaleRegister.new(params[:sale_register])

    respond_to do |format|
      if @sale_register.save
        format.html { redirect_to(@sale_register, :notice => 'Sale register was successfully created.') }
        format.xml  { render :xml => @sale_register, :status => :created, :location => @sale_register }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sale_register.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sale_registers/1
  # PUT /sale_registers/1.xml
  def update
    @sale_register = SaleRegister.find(params[:id])

    respond_to do |format|
      if @sale_register.update_attributes(params[:sale_register])
        format.html { redirect_to(@sale_register, :notice => 'Sale register was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sale_register.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_registers/1
  # DELETE /sale_registers/1.xml
  def destroy
    @sale_register = SaleRegister.find(params[:id])
    @sale_register.destroy

    respond_to do |format|
      format.html { redirect_to(sale_registers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sale_registers_helper.rb
module SaleRegistersHelper
end

app/views/sale_registers/_form.html.erb
<%= simple_form_for(@sale_register) do |f| %>
  <% if @sale_register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale_register.errors.count, "error") %> prohibited this sale_register from being saved:</h2>

      <ul>
      <% @sale_register.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.input :process_register_id %>
    <%= f.input :buy_date, :as => :date, :start_year => Date.today.year - 10,
				:end_year => Date.today.year,:order => [:day, :month, :year] %>
    <%= f.input :value %>
 	<%= f.association :seller, :include_blank => false %>
    <%= f.button :submit %>
<% end %>

app/views/sale_registers/edit.html.erb
<h1>Editing sale_register</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale_register %> |
<%= link_to 'Back', sale_registers_path %>

app/views/sale_registers/index.html.erb
<h1>Listing sale_registers</h1>

<table>
  <tr>
    <th>Buy date</th>
    <th>Value</th>
    <th>Seller</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sale_registers.each do |sale_register| %>
  <tr>
    <td><%= sale_register.buy_date	 %></td>
    <td><%= sale_register.value %></td>
    <td><%= sale_register.seller.name %></td>
    <td><%= link_to 'Show', sale_register %></td>
    <td><%= link_to 'Edit', edit_sale_register_path(sale_register) %></td>
    <td><%= link_to 'Destroy', sale_register, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sale register', new_sale_register_path %>

app/views/sale_registers/new.html.erb
<h1>New sale_register</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_registers_path %>

app/views/sale_registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sale_register %>
</p>

<p>
  <b>Customer:</b>
  <%= @sale_register%>
</p>

<p>
  <b>Data buy:</b>
  <%= @sale_register.buy_date %>
</p>

<p>
  <b>Value:</b>
  <%= @sale_register.value %>
</p>

<p>
  <b>Vehicle:</b>
  <%= @sale_register %>
</p>

<p>
  <b>Seller:</b>
  <%= @sale_register.seller.name %>
</p>


<%= link_to 'Edit', edit_sale_register_path(@sale_register) %> |
<%= link_to 'Back', sale_registers_path %>