config/routes.rb
Regiauto::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'auth', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }  

  resources :process_registers do
    get 'delivery_status', :on => :member 
  end
   
  resources :vehicles, :hypothecs, :proprietary_registers, :sale_registers, :books, :main_registers, :proprietaries
  resources :home, :only => :index 
  

  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Regiauto <%= yield :title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, "jquery.tokeninput", "cocoon" %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div class="head">
 	<label class="lbs">Registo Automóvel</label>
	<div class="logout">
		<%= link_to t(:logout), destroy_user_session_path %>
	</div>
	<div class="userDetails">
		<b><%= t(:username, :scope => "layouts.application")%>: </b><label><%=current_user.full_name%></label> | 		
		<b><%= t(:profile, :scope => "layouts.application")%>: </b><label><%=current_user.profile %></label></br>
		<b><%= t(:last_sign_in, :scope => "layouts.application")%>: </b><label><%=l(current_user.last_sign_in_at)%></label>
	</div>
 </div>
<div class="conteiner">	
	<div class="navigation">
	  <ul class="orderedList">
		<li><%= link_to t(:home, :scope => "layouts.application"), home_index_path %></li>
	    <li><%= link_to t(:process, :scope => "layouts.application"), process_registers_path %></li>
		<li><%= link_to t(:proprietaries, :scope => "layouts.application"), proprietaries_path %></li>
		<li><%= link_to t(:vehicles, :scope => "layouts.application"), vehicles_path %></li>
	  </ul>
	</div>
	<div class="content">
		<div class="products">
			<p class="alert"><%= alert %></p>	
			<%= yield %>
		</div>
	</div>
	<div class="footer"> Desenvolvido por Stélio Moiane © 2013</div>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Regiauto <%= yield :title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div class='login_content'>  
	<div class='top'>
		<%=image_tag("logo.gif",:size =>"90x90")%>
		<p>Sistema de Gestão de Registo Automóvel</p>
		<p>REGIAUTO</p>
	</div>
	<div class="login">
		<p class="alert"><%= alert %></p>	
		<%= yield %>
	</div>
 </div>
</body>
</html>